ACTIVITY_CONFIG = [
  { "key": "100", "name": "running", "name_zh": "跑步/路跑" },
  { "key": "101", "name": "treadmill_running", "name_zh": "跑步机/室内跑" },
  { "key": "102", "name": "trail_running", "name_zh": "越野跑" },
  { "key": "103", "name": "track_running", "name_zh": "操场跑" },
  { "key": "200", "name": "cycling", "name_zh": "户外骑行" },
  { "key": "201", "name": "indoor_cycling", "name_zh": "室内骑行" },
  { "key": "202", "name": "mountain_biking", "name_zh": "山地骑行" },
  { "key": "300", "name": "swimming", "name_zh": "游泳" },
  { "key": "301", "name": "lap_swimming", "name_zh": "泳池游泳" },
  { "key": "302", "name": "open_water_swimming", "name_zh": "公开水域游泳" },
  { "key": "400", "name": "hiking", "name_zh": "徒步/登山" },
  { "key": "500", "name": "fitness_equipment", "name_zh": "健身设备/爬楼机" },
  { "key": "501", "name": "strength_training", "name_zh": "力量训练" },
  { "key": "502", "name": "cardio_training", "name_zh": "室内健身/有氧/HIIT" },
  { "key": "503", "name": "yoga", "name_zh": "瑜伽" },
  { "key": "505", "name": "rowing", "name_zh": "室内划船机" },
  { "key": "600", "name": "winter_sports", "name_zh": "冬季运动" },
  { "key": "601", "name": "resort_skiing_snowboarding_ws", "name_zh": "单双板滑雪" },
  { "key": "602", "name": "backcountry_skiing_snowboarding_ws", "name_zh": "越野滑雪" },
  { "key": "700", "name": "walking", "name_zh": "步行/健步走" },
  { "key": "800", "name": "water_sports", "name_zh": "水上运动/尾波冲浪" },
  { "key": "801", "name": "rowing_v2", "name_zh": "皮划艇/户外划船" },
  { "key": "802", "name": "paddlesports", "name_zh": "桨板 (SUP)" },
  { "key": "803", "name": "whitewater_rafting_keyaking", "name_zh": "白水漂流/激流皮划艇" },
  { "key": "804", "name": "surfing", "name_zh": "冲浪" },
  { "key": "805", "name": "windsurfing", "name_zh": "风筝冲浪/风帆冲浪" },
  { "key": "806", "name": "sailing", "name_zh": "航海/帆船" },
  { "key": "900", "name": "other", "name_zh": "其他" }
]