name: 定时备份 FIT 文件到存储

# 定义触发事件
on:
  schedule:
    # 每天执行两次（每天 00:00 和 12:00）
    - cron: "0 0,12 * * *"
  workflow_dispatch: # 可手动触发

jobs:
  backup-fit:
    runs-on: ubuntu-latest
    steps:
      - name: 定时备份 FIT 文件到存储
        run: |
          echo "开始备份 FIT 文件到对象存储..."
          RESPONSE=$(curl -s -X GET "https://i.incremental.icu/api/v1/base/batchUploadFitToStorage?limit=5" -H "Content-Type: application/json")
          echo "接口返回: $RESPONSE"
